version: 2
updates:
  - package-ecosystem: "npm"
    directory:
      - "/src"
    open-pull-requests-limit: 1
    schedule:
      interval: weekly
      day: saturday
      time: "10:00"
      timezone: "Asia/Tokyo"
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
      directories:
        - "/docker"
      open-pull-requests-limit: 1
      schedule:
        interval: weekly
        day: saturday
        time: "10:00"
        timezone: "Asia/Tokyo"
