services:
  monaka:
    container_name: ${APP_CONTAINER_NAME:-monaka_app}
    build:
      context: .
      dockerfile: ./docker/nodejs/Dockerfile.ubuntu
      args:
        NODE_VERSION: ${NODE_VERSION:-22}
        USER_ID: ${USER_ID:-1001}
        GROUP_ID: ${GROUP_ID:-1001}
        USER_NAME: ${USER_NAME:-devstaff}
      target: development
    user: ${USER_NAME:-devstaff}
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    ports:
      - "8888:3000"
    volumes:
      - type: volume
        source: monaka-src-store
        target: /workspaces/monaka/src
      - type: volume
        source: monaka-docs-store
        target: /workspaces/monaka/docs
        volume:
          nocopy: true
      - /workspaces/monaka/src/node_modules
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 3
    develop:
      watch:
        - action: rebuild
          path: src/app.js
  e2e:
    container_name: ${E2E_CONTAINER_NAME:-monaka_e2e}
    build:
      context: .
      dockerfile: docker/playwright/Dockerfile
      args:
        PLAYWRIGHT_VERSION: ${PLAYWRIGHT_VERSION:-v1.53.1}
    user: ${E2E_USER_NAME:-pwuser}
    ports:
      - "9323:9323"
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 3
volumes:
  monaka-src-store:
    driver: local
    driver_opts:
      type: none
      device: ./src
      o: bind
  monaka-docs-store:
    driver: local
    driver_opts:
      type: none
      device: ./docs
      o: bind
