services:
  monaka:
    build:
      context: .
      dockerfile: ./docker/nodejs/Dockerfile
      target: local
    user: monakadev
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - "8888:3000"
    volumes:
      - monaka-src-store:/home/monakadev/monaka/src
      - monaka-docs-store:/home/monakadev/monaka/docs
      - /home/monakadev/monaka/src/node_modules
volumes:
  monaka-src-store:
    driver: local
    driver_opts:
      type: none
      device: ./src
      o: bind
  monaka-docs-store:
    driver: local
    driver_opts:
      type: none
      device: ./docs
      o: bind
