name: "Deploy"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_deploy:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        language: ["javascript"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
